name: "Create .envs file"
description: "Github Action to create a .envs file with Github Secrets"
author: "Forest Anderson"
branding:
  icon: "briefcase"
  color: "gray-dark"
inputs:
  file_name:
    description: "The filename for the envfile"
    default: ".env"
  directory:
    description: "The directory to put the envfile in"
    default: ""
  fail_on_empty:
    description: "Fail if an env key is an empty string"
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
